category-template: '### $TITLE'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'accessibility'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'maintenance'
  - title: '📖 Documentation'
    label: 'documentation'
  - title: '🎨 Tokens'
    labels:
      - 'update-colors'
      - 'update-icons'
      - 'update-illustrations'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'
  - 'automation'
template: |
  Changes in this release:
  $CHANGES
