name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: set -o pipefail && xcodebuild -scheme Orbit -destination "generic/platform=iOS Simulator" | xcpretty
