name: Publish DocC

on:
  push:
    branches: [ main ]

jobs:
  documentation:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - name: Generate DocC
      run: |
        mkdir -p docs
        set -o pipefail && xcodebuild docbuild \
          -scheme Orbit \
          -destination "generic/platform=iOS" \
          OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs" \
          | xcpretty
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: docc
        folder: docs
        target-folder: docs
