name: Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        description: "The version/tag for this release"
        required: true
      changelog:
        description: "What's new in this release"
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - run: -|
           echo "Version - ${{ github.event.inputs.version }}"
           echo "Changelog - ${{ github.event.inputs.changelog }}"
