name: Snapshot Updater

on:
  issue_comment:
    types: [created]

jobs:
  update_trigger:
    runs-on: macos-12
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: 'update_snapshots'
  generate_snapshots:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SNAPSHOT_PUSH_TOKEN }}
      - name: generate
        run: |
          Automation/generate_snapshots.sh
      - name: upload
        run: |
            git config --global user.name "Mobile Automation"
            git config --global user.email "mobile.automation@kiwi.com"
            git commit am "Updated snapshots."
            git push
